import type { QueuedSong } from '@/types/player'

export const mockQueue: QueuedSong[] = [
  {
    id: '1',
    youtubeId: 'dQw4w9WgXcQ',
    title: 'Never Gonna Give You Up',
    artist: 'Rick Astley',
    thumbnailUrl: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/default.jpg',
    duration: 212,
    donationId: 'donation-1',
    donorName: 'CoolViewer42',
    donationAmount: 5.00,
    message: 'This song always makes me smile!',
    requestedAt: new Date('2026-03-10T10:00:00Z'),
    position: 1,
  },
  {
    id: '2',
    youtubeId: 'kJQP7kiw5Fk',
    title: 'Despacito',
    artist: 'Luis Fonsi',
    thumbnailUrl: 'https://i.ytimg.com/vi/kJQP7kiw5Fk/default.jpg',
    duration: 279,
    donationId: 'donation-2',
    donorName: 'MusicLover99',
    donationAmount: 10.00,
    message: 'Please play this for my birthday!',
    requestedAt: new Date('2026-03-10T10:05:00Z'),
    position: 2,
  },
  {
    id: '3',
    youtubeId: '9bZkp7q19f0',
    title: 'Gangnam Style',
    artist: 'PSY',
    thumbnailUrl: 'https://i.ytimg.com/vi/9bZkp7q19f0/default.jpg',
    duration: 253,
    donationId: 'donation-3',
    donorName: 'KPopFan',
    donationAmount: 3.50,
    requestedAt: new Date('2026-03-10T10:10:00Z'),
    position: 3,
  },
  {
    id: '4',
    youtubeId: 'RgKAFK5djSk',
    title: 'Wrecking Ball',
    artist: 'Miley Cyrus',
    thumbnailUrl: 'https://i.ytimg.com/vi/RgKAFK5djSk/default.jpg',
    duration: 231,
    donationId: 'donation-4',
    donorName: 'StreamWatcher',
    donationAmount: 7.25,
    message: 'Love this track!',
    requestedAt: new Date('2026-03-10T10:15:00Z'),
    position: 4,
  },
]

export const mockCurrentSong: QueuedSong = {
  id: '1',
  youtubeId: 'dQw4w9WgXcQ',
  title: 'Never Gonna Give You Up',
  artist: 'Rick Astley',
  thumbnailUrl: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/default.jpg',
  duration: 212,
  donationId: 'donation-1',
  donorName: 'CoolViewer42',
  donationAmount: 5.00,
  message: 'This song always makes me smile!',
  requestedAt: new Date('2026-03-10T10:00:00Z'),
  position: 1,
}
